schema_version: '2.0'
directory_name: sdk
description: GAIA Software Development Kit providing comprehensive APIs, tools, and
  frameworks for building applications that integrate with the Global Artificial Intelligence
  Architecture.
semantic_scope:
- gaia_sdk
- development_kit
- apis
- frameworks
- integration_tools
- application_development
- gaia_integration
files: []
child_directories:
- assessment
- core
- dynamics
- learning
- storage
