schema_version: '2.0'
directory_name: plots
description: Generated plots, charts, and visual analytics from GAIA training sessions
  including learning curves, performance graphs, and data visualizations.
semantic_scope:
- plots
- charts
- visualizations
- learning_curves
- performance_graphs
- data_visualization
- training_analytics
files: []
child_directories: []
