schema_version: '2.0'
directory_name: noisy_sine
description: The noisy_sine directory is reserved for noisy functionality. It provides
  a dedicated space for organizing related files and components.
semantic_scope:
- noisy
- sine
files:
- entropy_evolution_noisy_sine.png
- feedback_accuracy_noisy_sine.png
- feedback_geometry_pca_100.png
- feedback_geometry_pca_120.png
- feedback_geometry_pca_140.png
- feedback_geometry_pca_160.png
- feedback_geometry_pca_180.png
- feedback_geometry_pca_20.png
- feedback_geometry_pca_40.png
- feedback_geometry_pca_60.png
- feedback_geometry_pca_80.png
- fractal_dim_evolution_noisy_sine.png
- hidden_layer_size_evolution_noisy_sine.png
- loss_evolution_noisy_sine.png
- loss_evolution_overlay_noisy_sine.png
- planck_weights_step_0.png
- planck_weights_step_100.png
- planck_weights_step_150.png
- planck_weights_step_50.png
- pred_vs_truth_noisy_sine.png
- pred_vs_truth_overlay_noisy_sine.png
- weight_hist_0.png
- weight_hist_10.png
- weight_hist_100.png
- weight_hist_110.png
- weight_hist_120.png
- weight_hist_130.png
- weight_hist_140.png
- weight_hist_150.png
- weight_hist_160.png
- weight_hist_170.png
- weight_hist_180.png
- weight_hist_190.png
- weight_hist_20.png
- weight_hist_30.png
- weight_hist_40.png
- weight_hist_50.png
- weight_hist_60.png
- weight_hist_70.png
- weight_hist_80.png
- weight_hist_90.png
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 42
  directory_count: 0
  primary_file_types:
    .png: 41
    .yaml: 1
