schema_version: '2.0'
directory_name: 20250904_164755_c8380ac9
description: Long-term training session from September 4, 2025 (16:47:55) with identifier
  c8380ac9, containing comprehensive training outputs, performance metrics, and analysis
  data from extended GAIA learning cycle.
semantic_scope:
- training_session
- timestamped_output
- session_20250904_164755
- training_results
- performance_data
- learning_cycle
- session_c8380ac9
files: []
child_directories:
- dashboards
- debug
- logs
- metrics
- plots
- raw_data
