schema_version: '2.0'
directory_name: dawn-models
description: >
  Dawn Models is the official model repository for the Dawn Field Institute, 
  implementing cutting-edge post-symbolic AI architectures including CIMM 
  (Cosmic Information Mining Model), TinyCIMM variants for symbolic cognition, 
  and SCBF (Symbolic Collapse Bifractal Framework) for interpretability analysis.
  Features dual-licensing strategy with experimental research models (AGPL-3.0) 
  and stable production models (Apache-2.0). Demonstrates entropy-informed 
  architectures achieving adaptive learning, symbolic memory, and field-based 
  intelligence using Dawn Field Theory principles.
semantic_scope:
- models
- post-symbolic-ai
- cimm
- tinycimm
- scbf
- symbolic-collapse
- field-theory
- entropy-dynamics
files:
- CONTRIBUTING.md
- LICENSE
- LICENSING.md
- README.md
child_directories:
- .cip
- research
- stable
title: dawn-models
repository_role: models
generation_context:
  generator: ai_enhanced
  file_count: 5
  directory_count: 3
  primary_file_types:
    .md: 3
    .yaml: 1
