schema_version: '2.0'
directory_name: raw_data
description: Raw unprocessed data from GAIA training sessions including input datasets,
  intermediate computational results, and unfiltered training outputs.
semantic_scope:
- raw_data
- unprocessed_data
- input_datasets
- computational_results
- training_outputs
- data_collection
- unfiltered_data
files: []
child_directories: []
