schema_version: 2.0
directory_name: modules
description: 'Modules and subcomponents for the GAIA model architecture.

  '
semantic_scope:
- modules
- architecture
- GAIA
files:
- collapse_core.md
- field_engine.md
- meta_cognition_layer.md
- resonance_mesh.md
- superfluid_memory.md
- symbolic_crystallizer.md
child_directories: []
