schema_version: '2.0'
directory_name: scbf
description: >
  SCBF (Symbolic Collapse Bifractal Framework) - Core interpretability framework
  that measures symbolic collapse and bifractal patterns in neural network weight
  evolution. Provides insight into deep mathematical structures that emerge during
  learning through entropy analysis. Includes experiment runner, metrics analysis,
  visualization tools, and comprehensive testing suite for TinyCIMM integration.
semantic_scope:
- scbf
- interpretability
- symbolic-collapse
- bifractal
- neural-analysis
- entropy-metrics
files:
- __init__.py
- README.md
- scbf_runner.py
- test_scbf.py
- tinycimm_scbf_experiment.py
child_directories:
- docs
- loggers
- metrics
- scbf_experiments
- utils
- visualization
generation_context:
  generator: ai_enhanced
  file_count: 6
  directory_count: 6
  primary_file_types:
    .py: 4
    .yaml: 1
    .md: 1
