schema_version: '2.0'
directory_name: archive
description: GAIA application archive containing historical training outputs, experiment
  results, execution logs, and preserved application states for analysis and reference.
semantic_scope:
- archive
- historical_data
- training_outputs
- experiment_results
- execution_logs
- data_preservation
- analysis_records
files: []
child_directories:
- extended_training_logs
