schema_version: '2.0'
directory_name: TinyCIMM-Navier
description: The TinyCIMM-Navier directory contains Python modules implementing navier
  functionality. It houses the core logic and implementation details for this component
  of the system.
semantic_scope:
- navier
- tinycimm
files:
- README.md
- SCBF_NEURAL_DYNAMICS_ANALYSIS.md
- tinycimm_navier.py
child_directories:
- experiments
generation_context:
  generator: ai_enhanced
  file_count: 4
  directory_count: 1
  primary_file_types:
    .yaml: 1
    .md: 2
    .py: 1
