schema_version: '2.0'
directory_name: utils
description: The utils directory provides utility functions and helper modules used
  throughout the CIP codebase. It contains common functionality for file operations,
  data processing, and system interactions.
semantic_scope:
- utilities
- helpers
files:
- __init__.py
- scbf_utils.py
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 0
  primary_file_types:
    .py: 2
    .yaml: 1
