schema_version: '2.0'
directory_name: utils
description: This directory is part of the SCBF (Symbolic Collapse Bifractal Framework)
  research project. It contains various utility functions and helpers used in implementing
  the framework's functionality, including symbolic entropy collapse, bifractal collapse,
  and epistemic feedback mechanisms. The directory structure includes a YAML file
  that defines the schema version and provides a brief description of the directory's
  purpose. Additionally, there are two Python files containing the shared utility
  functions, an initialization file, and various other documentation assets. The content
  of this directory is focused on providing support for the SCBF framework, which
  is a research-oriented project that uses live entropy feedback, wave collapse equilibrium,
  and recursive field dynamics to build post-symbolic artificial intelligence.
semantic_scope:
- symbolic
- collapse
- bifractal
- epistemic
- feedback
files:
- __init__.py
- scbf_utils.py
child_directories: []
