schema_version: '2.0'
directory_name: docs
description: 'Documentation for the GAIA model, including theory, protocols, meta
  information, experiments, and architecture.

  '
semantic_scope:
- documentation
- GAIA
files:
- GAIA_v2_upgrade_summary.md
- testing_plan.md
- testing_strategy_v2.md
child_directories:
- architecture
- experiments
- meta
- protocols
- theory
