schema_version: '2.0'
directory_name: stable
description: >
  Production-ready stable models including CIMM-Legacy implementation.
  All stable models licensed under Apache-2.0 for commercial adoption
  and enterprise integration. Contains battle-tested implementations
  of Dawn Field Theory principles suitable for production deployment.
semantic_scope:
- stable
- production
- cimm
- commercial
- apache-licensed
files:
- LICENSE
child_directories:
- cimm-legacy
generation_context:
  generator: ai_enhanced
  file_count: 2
  directory_count: 1
  primary_file_types:
    .yaml: 1
