schema_version: '2.0'
directory_name: tinycimm
description: >
  TinyCIMM (Tiny Categorical Information Memory Matrix) - Ultra-minimal agentic
  models for symbolic cognition and recursive collapse. Demonstrates how lightweight,
  entropy-informed architectures achieve adaptive learning, symbolic memory, and
  field-based intelligence using Dawn Field Theory principles. Includes specialized
  variants: Euler (number theory), Planck (minimal foundational), and Navier 
  (fluid dynamics).
semantic_scope:
- tinycimm
- minimal-ai
- symbolic-cognition
- entropy-dynamics
- field-intelligence
- adaptive-learning
files:
- README.md
- TinyCIMM_naming.md
child_directories:
- TinyCIMM-Euler
- TinyCIMM-Navier
- TinyCIMM-Planck
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 3
  primary_file_types:
    .yaml: 1
    .md: 2
