schema_version: 2.0
directory_name: architecture
description: 'Architecture documentation and supporting files for the GAIA model.

  '
semantic_scope:
- architecture
- GAIA
files:
- overview.md
child_directories:
- modules
