schema_version: '2.0'
directory_name: models
description: The models directory is a Python package containing models modules and
  functionality. It provides a structured collection of related code organized for
  easy import and use.
semantic_scope:
- models
- ai_ml
files:
- __init__.py
- base_cimm_model.py
- cryptography_model.py
- financial_model.py
- prime_structure_model.py
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 6
  directory_count: 0
  primary_file_types:
    .py: 5
    .yaml: 1
