schema_version: '2.0'
directory_name: experiment_logs
description: The experiment_logs directory organizes monitoring components into logical
  subdirectories. It serves as a container for related functionality, with each subdirectory
  focusing on specific aspects of monitoring.
semantic_scope:
- monitoring
- logging
- experiment
files:
- clean_sine_log.csv
- tinycimm_planck_amp_mod_sine_log.csv
- tinycimm_planck_chaotic_sine_log.csv
- tinycimm_planck_clean_sine_log.csv
- tinycimm_planck_freq_mod_sine_log.csv
- tinycimm_planck_noisy_sine_log.csv
- TinyplanckPlanck_planck_amp_mod_sine_log.csv
- TinyplanckPlanck_planck_amp_mod_sine_metrics.csv
- TinyplanckPlanck_planck_chaotic_sine_log.csv
- TinyplanckPlanck_planck_clean_sine_log.csv
- TinyplanckPlanck_planck_clean_sine_metrics.csv
- TinyplanckPlanck_planck_freq_mod_sine_log.csv
- TinyplanckPlanck_planck_mlp_amp_mod_sine_log.csv
- TinyplanckPlanck_planck_mlp_chaotic_sine_log.csv
- TinyplanckPlanck_planck_mlp_clean_sine_log.csv
- TinyplanckPlanck_planck_mlp_freq_mod_sine_log.csv
- TinyplanckPlanck_planck_mlp_noisy_sine_log.csv
- TinyplanckPlanck_planck_noisy_sine_log.csv
child_directories:
- amp_mod_sine
- chaotic_sine
- clean_sine
- freq_mod_sine
- noisy_sine
generation_context:
  generator: ai_enhanced
  file_count: 19
  directory_count: 5
  primary_file_types:
    .csv: 18
    .yaml: 1
