schema_version: '2.0'
directory_name: freq_mod_sine
description: The freq_mod_sine directory is reserved for freq functionality. It provides
  a dedicated space for organizing related files and components.
semantic_scope:
- freq
- mod
- sine
files:
- TinyplanckPlanck_planck_freq_mod_sine_log.csv
- TinyplanckPlanck_planck_freq_mod_sine_metrics.csv
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 0
  primary_file_types:
    .yaml: 1
    .csv: 2
