schema_version: '2.0'
directory_name: scbf_experiments
description: The scbf_experiments directory contains experimental code and research
  materials for scbf. It houses exploratory work, prototypes, and research findings
  that may inform future development.
semantic_scope:
- scbf
- research
- experiments
files:
- '[cip][experiment][v1.0][2025-07-13]_scbf_interpretability_report.md'
- experiment_registry.json
child_directories:
- '20250713_101403'
- '20250713_101847'
- '20250713_102144'
- '20250713_102425'
- '20250713_102931'
- '20250713_104841'
- '20250714_104111'
- '20250714_104436'
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 8
  primary_file_types:
    .md: 1
    .json: 1
    .yaml: 1
