schema_version: '2.0'
directory_name: tinycimm_recursive_sequence_10000_7fe3c68f
description: "This directory contains a TinyCIMM (Tiny Categorical Information Memory\
  \ Matrix) configuration for the SCBF (Symbolic Collapse Bifractal Framework) experiment\
  \ with the ID \"7fe3c68f\" and duration of 82.5 seconds. The directory contains\
  \ 13 files, including a checkpoint file, an experiment summary file, a meta.yaml\
  \ file, and 10 code files.\n        The purpose of this directory is to store the\
  \ configuration and results of a SCBF (Symbolic Collapse Bifractal Framework) experiment\
  \ with the TinyCIMM (Tiny Categorical Information Memory Matrix) model for a recursive\
  \ sequence with 10,000 steps. The experiment summarizes the results of the model's\
  \ performance on a specific task or problem, providing insight into its ability\
  \ to adapt and learn from data."
semantic_scope:
- cimm
- tinycimm
files:
- checkpoint.json
- experiment_results.json
- experiment_summary.txt
child_directories:
- plots
