schema_version: '2.0'
directory_name: core
description: GAIA SDK core components providing fundamental APIs, base classes, and
  essential functionality for building GAIA-integrated applications and cognitive
  systems.
semantic_scope:
- core_components
- fundamental_apis
- base_classes
- essential_functionality
- gaia_core
- sdk_foundation
- core_architecture
files: []
child_directories: []
