schema_version: '2.0'
directory_name: TinyCIMM-Planck
description: >
  TinyCIMM-Planck focuses on quantum-inspired pattern analysis and activation-centered
  metrics for understanding neural dynamics at the finest granular level. Named after
  Max Planck for its emphasis on fundamental quantum-like discretization of neural
  activations and energy states, with bifractal collapse analysis and semantic 
  recursion capabilities.
semantic_scope:
- planck
- tinycimm
- quantum-inspired
- activation-dynamics
- bifractal-analysis
- semantic-recursion
- interpretability
files:
- README.md
- '[id][F][v1.0][C4][I5][E]_symbolic_collapse_interpretability.md'
- output.txt
- report.md
- tinycimm_planck.py
child_directories:
- docs
- experiment_images
- experiment_logs
- experiments
generation_context:
  generator: ai_enhanced
  file_count: 6
  directory_count: 4
  primary_file_types:
    .md: 3
    .yaml: 1
    .txt: 1
    .py: 1
