schema_version: '2.0'
directory_name: metrics
description: The metrics directory is a Python package containing metrics modules
  and functionality. It provides a structured collection of related code organized
  for easy import and use.
semantic_scope:
- metrics
files:
- __init__.py
- activation_ancestry.py
- bifractal_lineage.py
- entropy_collapse.py
- phase_alignment.py
- semantic_attractors.py
- validation.py
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 8
  directory_count: 0
  primary_file_types:
    .py: 7
    .yaml: 1
