schema_version: '2.0'
directory_name: plots
description: The plots directory is reserved for plots functionality. It provides
  a dedicated space for organizing related files and components.
semantic_scope:
- plots
files:
- bifractal_evolution.png
- complete_dashboard.png
- entropy_collapse.png
- neural_growth.png
- predictions_vs_actual.png
- quantum_metrics_analysis.png
- training_dynamics.png
- weight_analysis.png
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 9
  directory_count: 0
  primary_file_types:
    .png: 8
    .yaml: 1
