schema_version: '2.0'
directory_name: loggers
description: The loggers directory is a Python package containing loggers modules
  and functionality. It provides a structured collection of related code organized
  for easy import and use.
semantic_scope:
- loggers
files:
- __init__.py
- experiment_logger.py
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 0
  primary_file_types:
    .py: 2
    .yaml: 1
