schema_version: '2.0'
directory_name: freq_mod_sine
description: "The freq_mod_sine directory is a collection of files related to the\
  \ implementation of a sine wave frequency modulation (FMC) signal processing technique.\
  \ The directory contains 42 files, including both code and documentation files.\
  \ The first 10 code files are used for implementing the FMC algorithm, while the\
  \ first five documentation files provide an overview of the technique and its applications.\n\
  \        The purpose of this directory is to house all relevant materials related\
  \ to a specific signal processing technique, making it easier to manage and access\
  \ the information needed for development and testing purposes. It serves as a central\
  \ location for researchers and developers who need to study and develop FMC algorithms\
  \ for various applications."
semantic_scope:
- fmc
- algorithm
files:
- entropy_evolution_freq_mod_sine.png
- feedback_accuracy_freq_mod_sine.png
- feedback_geometry_pca_100.png
- feedback_geometry_pca_120.png
- feedback_geometry_pca_140.png
- feedback_geometry_pca_160.png
- feedback_geometry_pca_180.png
- feedback_geometry_pca_20.png
- feedback_geometry_pca_40.png
- feedback_geometry_pca_60.png
- feedback_geometry_pca_80.png
- fractal_dim_evolution_freq_mod_sine.png
- hidden_layer_size_evolution_freq_mod_sine.png
- loss_evolution_freq_mod_sine.png
- loss_evolution_overlay_freq_mod_sine.png
- planck_weights_step_0.png
- planck_weights_step_100.png
- planck_weights_step_150.png
- planck_weights_step_50.png
- pred_vs_truth_freq_mod_sine.png
- pred_vs_truth_overlay_freq_mod_sine.png
- weight_hist_0.png
- weight_hist_10.png
- weight_hist_100.png
- weight_hist_110.png
- weight_hist_120.png
- weight_hist_130.png
- weight_hist_140.png
- weight_hist_150.png
- weight_hist_160.png
- weight_hist_170.png
- weight_hist_180.png
- weight_hist_190.png
- weight_hist_20.png
- weight_hist_30.png
- weight_hist_40.png
- weight_hist_50.png
- weight_hist_60.png
- weight_hist_70.png
- weight_hist_80.png
- weight_hist_90.png
child_directories: []
