schema_version: '2.0'
directory_name: debug
description: Debug information and diagnostic data from GAIA training sessions including
  error traces, system state dumps, and troubleshooting artifacts.
semantic_scope:
- debug_data
- diagnostics
- error_traces
- system_state
- troubleshooting
- diagnostic_artifacts
- debugging_tools
files: []
child_directories: []
