schema_version: '2.0'
directory_name: metrics
description: Performance metrics and quantitative measurements from GAIA training
  including accuracy scores, learning rates, convergence data, and system performance
  indicators.
semantic_scope:
- performance_metrics
- quantitative_data
- accuracy_measurements
- learning_analytics
- convergence_tracking
- system_performance
- training_metrics
files: []
child_directories: []
