schema_version: '2.0'
directory_name: noisy_sine
description: The noisy_sine directory is reserved for noisy functionality. It provides
  a dedicated space for organizing related files and components.
semantic_scope:
- noisy
- sine
files:
- TinyplanckPlanck_planck_noisy_sine_log.csv
- TinyplanckPlanck_planck_noisy_sine_metrics.csv
child_directories: []
generation_context:
  generator: ai_enhanced
  file_count: 3
  directory_count: 0
  primary_file_types:
    .yaml: 1
    .csv: 2
