schema_version: '2.0'
directory_name: storage
description: GAIA storage systems providing persistent data management, memory storage,
  knowledge base management, and data persistence layers for cognitive architectures.
semantic_scope:
- storage_systems
- data_management
- memory_storage
- knowledge_bases
- data_persistence
- cognitive_storage
- information_management
files: []
child_directories: []
