schema_version: 2.0
directory_name: GAIA
description: 'GAIA framework models, documentation, and protocols for Dawn Field Theory.

  '
semantic_scope:
- GAIA
- model
- protocol
files:
- gaia_runtime.py
- phase3_agi_validation_report.md
child_directories:
- applications
- long_term_training_output
- modules
- sdk
- src
- tests
