schema_version: '2.0'
directory_name: cimm_core
description: The cimm_core directory is a Python package containing cimm modules and
  functionality. It provides a structured collection of related code organized for
  easy import and use.
semantic_scope:
- cimm
- core
files:
- __init__.py
- cimm.py
- cimm_core.py
- cimm_core_manager.py
- utils.py
child_directories:
- entropy
- learning
- models
- optimization
generation_context:
  generator: ai_enhanced
  file_count: 6
  directory_count: 4
  primary_file_types:
    .py: 5
    .yaml: 1
